-- AgentRole 默认 Agent 槽位：新增「外部引擎 Agent 名」（todo 2，opencode-native-permissions-and-fixes）。
--
-- 背景：`agent_roles.default_agent_id` 是指向 `agents.id` 的 FK，只能引用平台自有 Agent；
-- 而一个角色也应能指名**外部引擎 Agent**（opencode serve `GET /agent` 清单里的原生 agent，
-- 如 `Prometheus - Plan Builder`）。本迁移新增可空列 `default_opencode_agent_name` 承载它，
-- 与原 FK 列构成「至多一个被占用」的单一槽位：
--
--   不变式（service 层强制，DDL 无法表达跨列约束而不引触发器）：
--     至多一个 of (`default_agent_id`, `default_opencode_agent_name`) 非空；
--     写入违规 → 400 `AGENT_ROLE_DEFAULT_SLOT_CONFLICT`；设置其一自动清空另一个。
--
-- 语义（写入侧，见 `src/agent-roles/agent-roles.service.ts`）：
--   - `default_agent_id`：内部 Agent，须存在（`assertAgentExists`，不存在 → 400
--     `AGENT_ROLE_DEFAULT_AGENT_NOT_FOUND`）；被绑 Agent 删除时 SetNull（列 FK，不变）。
--   - `default_opencode_agent_name`：外部引擎名，**弱校验**（能取到 worker 的 agent 清单则
--     核对并告警、绝不阻断写入，镜像 teams.service `warnIfOpencodeAgentUnknown`）；
--     权威判定在执行期（名不存在由 opencode 报错回流 agent.status）。名字含空格/大写，
--     原样保存（不规范化），故列用 utf8mb4 兼容长度 `VARCHAR(128)`：
--     线上实测最长 25 字符（`Prometheus - Plan Builder`），128 留足余量且低于
--     utf8mb4 索引键上限保守值（MySQL 8 InnoDB 默认 DYNAMIC 行格式允许 3072 字节键，
--     本列不加索引；同时对齐本库其余短文本列的 varchar(191) 惯例以下）。
--
--   - 外部名不做机器格式校验（`AGENT_KEY_PATTERN` 是小写 machine-safe 键，不适用于
--     display 名，如 `Prometheus - Plan Builder` 含空格/大写）；DTO 只限 `@MaxLength(128)`。
--
-- 本迁移为**加法-only**（additive nullable column）：不触碰任何存量行，7 个 builtin 角色
-- 的 `default_agent_id` 与其余列逐字节不变，`default_opencode_agent_name` 全为 NULL
-- （即「内部槽位」语义与迁移前完全一致）。无数据回填。
--
-- ⚠️ 回滚（精确命令；本条为可逆迁移，drop 回去即恢复迁移前 schema——但会丢弃迁移后写入的
--   外部名数据，故执行前先确认无在用外部绑定）：
--
--     docker compose exec -T db sh -c 'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" aiagents' <<'SQL'
--     ALTER TABLE `agent_roles` DROP COLUMN `default_opencode_agent_name`;
--     SQL
--
--   或（等价，Prisma 侧）：先 `npx prisma migrate resolve --rolled-back 20260919000011_agent_role_external_agent`，
--   再手工 DROP COLUMN（Prisma 无自动 down 迁移）。
--
-- 适用时机：全新库路径下为纯 DDL（建表后 agent_roles 为空，无行可影响）。
ALTER TABLE `agent_roles`
  ADD COLUMN `default_opencode_agent_name` VARCHAR(128) NULL;
