/**
 * Phase 5 T9 · 17 页 data-testid 全量清单（reference）
 * =============================================
 * 事实依据：
 * - .omo/evidence/prototype-audit.md（Phase 0 审计，17 页全量清单）
 * - web/app/ 迁移实现（grep data-testid 实测，T4/T5 补充：skills 实际 25、
 *   tool-register 56 + register-feedback；各页新增 loading/error/retry 等反馈 testid）
 * - 导航变体三页（nav-cmdk/nav-hybrid/nav-rail）无独立路由——AppShell 融合导航
 *   （NavTopBar + NavDock + CmdKPanel，nav-hybrid 心智终态）统一承载，对应 testid
 *   在 app-shell/nav-top-bar/nav-dock/cmdk-panel 组件中。
 *
 * 用途：T9 断言代表性子集时对照全量；T10 终检复用此清单。
 */

/** 融合导航（AppShell）testid——覆盖 nav-cmdk/nav-hybrid/nav-rail 三变体的导航部分。 */
export const NAV_SHELL_TESTIDS = [
  "app-shell",
  "app-content",
  "topbar",
  "top-breadcrumb",
  "top-title",
  "rail-bar",
  "rail-icon",
  "rail-panel",
  "nav-item",
  "cmdk-trigger",
  "cmdk-panel",
  "cmdk-search",
  "cmdk-item",
  "cmdk-close",
  "logout-button",
  "canvasui-select",
] as const;

export interface PageTestidRef {
  /** 审计报告页面序号与名称 */
  auditPage: string;
  /** 迁移后路由（query 参数为必需参数） */
  route: string;
  /** 全量 testid（迁移后实测；含条件渲染区块） */
  testids: string[];
  /** 页面 root testid */
  root: string;
}

/** 17 页全量清单（按审计顺序；导航变体三页标注 AppShell 承载） */
export const PAGES: PageTestidRef[] = [
  {
    auditPage: "1.1 login（登录）",
    route: "/login",
    root: "username",
    testids: [
      "username",
      "password",
      "remember-me",
      "forgot-password-link",
      "login-button",
      "register-link",
      "login-error",
      "forgot-account",
      "forgot-submit",
      "forgot-error",
      "reset-token-input",
      "reset-new-password",
      "reset-confirm-password",
      "reset-submit",
      "reset-error",
      "reset-success",
      "back-to-login",
    ],
  },
  {
    auditPage: "1.2 team-list（团队列表，主工作台；项目列表已随项目维度拆除）",
    route: "/teams",
    root: "teams-list-root",
    testids: [
      "teams-list-root",
      "team-card",
      "create-team-button",
      "teams-search",
      "team-reuse-badge",
      "enter-team-session",
      "teams-loading",
      "teams-error",
      "teams-retry",
      "create-team-empty",
    ],
  },
  {
    auditPage: "1.3 task-create（创建任务）",
    route: "/tasks/new",
    root: "task-create-root",
    testids: [
      "task-create-root",
      "task-title",
      "task-description",
      "doc-upload",
      "doc-upload-btn",
      "doc-file-input",
      "doc-file-item",
      "doc-file-remove",
      "doc-upload-error",
      "doc-upload-error-dismiss",
      "priority-select",
      "team-select",
      "team-option",
      "team-member-preview-item",
      "reset-after-complete-toggle",
      "create-task-button",
      "create-hint",
      "create-success",
      "create-error",
      "title-error",
      "agents-loading",
      "agents-error",
      "agents-retry",
    ],
  },
  {
    auditPage: "1.4 task-board（任务看板）",
    route: "/board?teamId=tm_0000000001",
    root: "task-board-root",
    testids: [
      "task-board-root",
      "status-filter",
      "status-filter-option",
      "task-card",
      "task-members",
      "task-artifact-count",
      "start-task-button",
      "start-task-hint",
      "status-badge",
      "task-team-badge",
      "artifacts-entry-button",
      "board-title",
      "board-loading",
      "board-error",
      "board-retry",
    ],
  },
  {
    auditPage: "2.1 agent-config（Agent 配置）",
    route: "/agents",
    root: "agent-config-root",
    testids: [
      "agent-config-root",
      "agent-list-item",
      "clone-template-button",
      "model-config",
      "model-select",
      "model-option-provider",
      "model-token-status",
      "model-token-input",
      "model-credential-status",
      "agent-worker-select",
      "model-stale-warning",
      "model-source-hint",
      "skill-empty",
      "effective-permission-section",
      "effective-permission-empty",
      "effective-policy-meta",
      "effective-permission-scope",
      "effective-permission-row",
      "effective-mcp-loading",
      "effective-mcp-empty",
      "effective-mcp-group",
      "effective-mcp-group-toggle",
      "effective-mcp-tool",
      "prompt-editor",
      "skill-list",
      "agent-config-panel",
      "create-agent-button",
      "create-agent-modal",
      "agent-name-input",
      "agent-prompt-input",
      "create-agent-confirm",
      "create-agent-cancel",
      "create-agent-close",
      "create-agent-error",
      "save-agent-button",
      "agent-detail-loading",
      "agents-loading",
      "agents-error",
      "agents-retry",
      "agent-save-error",
      "persona-select",
    ],
  },
  {
    auditPage: "2.3b team-session（团队会话，唯一聊天入口）",
    route: "/teams/[id]/session（如 /teams/tm_0000000001/session）",
    root: "team-session-root",
    testids: [
      "team-session-root",
      "members-panel",
      "member-item",
      "dm-tabs",
      "dm-tab-group",
      "chat-message-list",
      "chat-load-more",
      "team-session-refresh",
      "team-session-current-task",
      "right-tab-status",
      "right-tab-config",
      "right-tab-output",
      "team-right-empty",
      "enter-team-session-drawer",
      "task-detail-drawer",
      "plan-doc-modal",
      "plan-doc-upload",
      "plan-doc-upload-input",
      "plan-doc-upload-error",
      "plan-status-block",
      "plan-status-badge",
      "plan-frozen-hash",
      "plan-frozen-version",
      "plan-version-line",
      "plan-round-progress",
      "plan-archive-block",
      "plan-archive-toggle",
      "plan-archive-item",
      "plan-confirm-btn",
      "plan-confirm-modal",
      "plan-confirm-cancel",
      "plan-confirm-confirm",
      "plan-finalize-btn",
      "plan-finalize-modal",
      "plan-finalize-cancel",
      "plan-finalize-confirm",
      "plan-checklist",
    ],
  },
  {
    auditPage: "2.4 nav-cmdk（导航变体 B）",
    route: "AppShell 承载（无独立路由，命令面板 testid 在 cmdk-panel 组件）",
    root: "cmdk-panel",
    testids: [
      "top-breadcrumb",
      "cmdk-trigger",
      "cmdk-panel",
      "cmdk-search",
      "cmdk-item",
      "task-info-header",
      "artifact-item",
      "artifact-viewer",
    ],
  },
  {
    auditPage: "2.5 nav-hybrid（导航融合版）",
    route: "AppShell 承载（无独立路由，nav-hybrid 心智为终态）",
    root: "app-shell",
    testids: [
      "nav-hybrid-root",
      "top-breadcrumb",
      "cmdk-trigger",
      "cmdk-panel",
      "cmdk-search",
      "cmdk-item",
      "rail-bar",
      "rail-icon",
      "rail-panel",
      "nav-item",
      "chat-message-list",
      "mention-hint",
      "task-info-panel",
      "artifact-link",
    ],
  },
  {
    auditPage: "2.6 nav-rail（导航变体 A）",
    route: "AppShell 承载（无独立路由，NavDock 即 rail 变体）",
    root: "rail-bar",
    testids: [
      "rail-bar",
      "rail-icon",
      "rail-panel",
      "nav-item",
      "chat-message-list",
      "mention-hint",
      "task-info-panel",
      "artifact-link",
      "topbar",
    ],
  },
  {
    auditPage: "2.7 role-permission（角色与权限）",
    route: "/system/roles",
    root: "role-permission-root",
    testids: [
      "role-permission-root",
      "role-item",
      "add-role-button",
      "permission-matrix",
      "permission-scope",
      "scope-inner-role-select",
      "permission-note",
      "create-role-button",
      "create-role-modal",
      "create-role-name-input",
      "create-role-confirm",
      "create-role-cancel",
      "create-role-close",
      "create-role-error",
      "delete-role-button",
      "save-role-button",
      "roles-saved",
      "roles-action-error",
      "roles-loading",
      "roles-error",
      "roles-retry",
    ],
  },
  {
    auditPage: "2.8 skills-tools-manage（技能与工具）",
    route: "/skills",
    root: "skills-tools-manage-root",
    testids: [
      "skills-tools-manage-root",
      "manage-toolbar",
      "manage-tabs",
      "manage-tab",
      "search-input",
      "upload-skill-button",
      "register-mcp-button",
      "manage-list",
      "manage-hint",
      "skill-item",
      "skill-source",
      "skill-status",
      "tool-subtabs",
      "tool-subtab",
      "tool-item",
      "tool-ready",
      "tool-kind",
      "tool-dep-status",
      "mcp-tool-item",
      "mcp-tool-name",
      "mcp-type",
      "mcp-status",
      "mcp-tool-status",
    ],
  },
  {
    auditPage: "2.9 task-detail（任务详情与文档库）",
    route: "/artifacts?teamId=tm_0000000001（产出物聚合页演化形态）",
    root: "artifacts-root",
    testids: [
      "artifacts-root",
      "artifacts-title",
      "artifacts-filter-bar",
      "task-filter-select",
      "type-filter-option",
      "accepted-filter-option",
      "artifact-row",
      "artifact-type-badge",
      "artifact-accepted-badge",
      "artifact-author",
      "artifact-version",
      "artifact-viewer",
      "artifact-version-switch",
      "artifact-version-timeline",
      "artifacts-loading",
      "artifacts-error",
      "artifacts-retry",
    ],
  },
  {
    auditPage: "2.11 user-management（用户管理）",
    route: "/system/users",
    root: "user-management-root",
    testids: [
      "user-management-root",
      "user-stats",
      "add-user-button",
      "user-item",
      "user-edit-button",
      "user-toggle-button",
      "user-reset-button",
      "user-role-badge",
      "user-status-badge",
      "user-form-overlay",
      "user-form-mask",
      "user-form",
      "user-form-close",
      "username-input",
      "user-email-input",
      "user-password-input",
      "user-role-select",
      "user-project-select",
      "user-form-cancel",
      "user-form-submit",
      "user-pool-hint",
      "user-form-error",
      "user-reset-form",
      "user-reset-overlay",
      "user-reset-password-input",
      "user-reset-submit",
      "user-reset-cancel",
      "users-action-error",
      "users-loading",
      "users-error",
      "users-retry",
      "edit-user-overlay",
      "edit-user-mask",
      "edit-user-form",
      "edit-user-close",
      "edit-username-input",
      "edit-user-email-input",
      "edit-user-role-select",
      "edit-user-error",
      "edit-user-cancel",
      "edit-user-submit",
    ],
  },
  {
    auditPage: "2.12 worker-install（新增 Worker）",
    route: "/workers/install",
    root: "worker-install-root",
    testids: [
      "worker-install-root",
      "install-wizard",
      "install-config",
      "server-url-input",
      "worker-id-input",
      "regenerate-worker-id-button",
      "capability-config",
      "install-method-section",
      "install-method-tabs",
      "install-method-tab",
      "install-command-section",
      "install-command",
      "copy-command-button",
      "install-steps",
      "install-footer",
      "install-confirm-button",
      "install-cancel-button",
    ],
  },
  {
    auditPage: "2.13 worker-list（Worker 节点管理）",
    route: "/workers",
    root: "worker-list-root",
    testids: [
      "worker-list-root",
      "worker-stats",
      "install-worker-link",
      "worker-card",
      "worker-status",
      "worker-version",
      "worker-capability",
      "worker-load",
      "worker-heartbeat",
      "worker-actions",
      "worker-detail-button",
      "worker-restart-button",
      "worker-offline-button",
      "worker-pool-hint",
      "worker-detail-models",
      "worker-model-badge",
      "worker-model-default",
      "workers-loading",
      "workers-error",
      "workers-retry",
    ],
  },
  {
    auditPage: "2.14 models-manage（模型管理：Provider 单一视图）",
    route: "/models",
    root: "models-manage-root",
    testids: [
      "models-manage-root",
      "providers-root",
      "providers-toolbar",
      "provider-search",
      "provider-list",
      "provider-item",
      "provider-id",
      "provider-model-count",
      "provider-credential-status",
      "provider-fingerprint",
      "provider-expand-toggle",
      "provider-models-panel",
      "provider-model-item",
      "provider-model-name",
      "provider-model-id",
      "provider-model-edit-button",
      "provider-model-capabilities-modal",
      "provider-model-capabilities-target",
      "provider-model-context-input",
      "provider-model-output-input",
      "provider-model-probe-button",
      "provider-model-reasoning-toggle",
      "provider-model-toolcall-toggle",
      "provider-model-temperature-toggle",
      "provider-model-attachment-toggle",
      "provider-model-capabilities-toggles",
      "provider-model-modalities-input",
      "provider-model-modalities-output",
      "provider-model-options-input",
      "provider-model-effort-select",
      "provider-model-capabilities-clear",
      "provider-model-capabilities-save",
      "provider-model-capabilities-cancel",
      "provider-model-capabilities-error",
      "provider-configure-button",
      "provider-edit-button",
      "provider-delete-button",
      "provider-config-modal",
      "provider-modal-provider",
      "provider-modal-key-input",
      "provider-modal-select-all",
      "provider-modal-workers",
      "provider-modal-save",
      "provider-modal-cancel",
      "provider-modal-error",
      "provider-edit-modal",
      "provider-edit-provider",
      "provider-edit-type",
      "provider-edit-baseurl-input",
      "provider-edit-modal-save",
      "provider-edit-modal-cancel",
      "provider-edit-modal-error",
      "provider-hint",
      "providers-loading",
      "providers-error",
      "providers-retry",
    ],
  },
];

/** 各页代表性断言 testid（T9 实际断言 3-5 个/页；数据行 testid 依赖 seed 数据） */
export const PAGE_SMOKE: Record<string, string[]> = {
  "/login": ["username", "password", "remember-me", "forgot-password-link", "login-button", "register-link"],
  "/register": ["register-username", "register-displayname", "register-password", "register-submit", "register-login-link"],
  "/teams": ["teams-list-root", "team-card", "create-team-button"],
  "/tasks/new": ["task-create-root", "task-title", "priority-select", "agent-option", "create-task-button", "instance-row", "instance-alias-input", "instance-workdir-input"],
  "/board": ["task-board-root", "status-filter", "task-card", "status-badge"],
  "/agents": ["agent-config-root", "agent-list-item", "model-select", "clone-template-button", "persona-select"],
  "/teams/[id]/session": ["team-session-root", "members-panel", "member-item", "dm-tabs", "dm-tab-group", "chat-message-list", "chat-load-more", "team-session-refresh", "team-session-current-task", "right-tab-status", "right-tab-config", "right-tab-output", "team-right-empty", "plan-doc-modal"],
  "/system/roles": ["role-permission-root", "role-item", "permission-matrix", "add-role-button"],
  "/skills": ["skills-tools-manage-root", "manage-tabs", "manage-tab", "search-input"],
  "/artifacts": ["artifacts-root", "artifacts-filter-bar", "task-filter-select"],
  "/system/users": ["user-management-root", "user-stats", "user-item", "add-user-button"],
  "/workers": ["worker-list-root", "worker-stats", "worker-card", "install-worker-link", "worker-status"],
  "/workers/[id]": ["worker-detail-basic", "worker-detail-runtime", "worker-detail-models", "worker-detail-omo", "omo-toggle"],
  "/workers/install": ["worker-install-root", "install-wizard", "install-config", "install-method-tabs", "install-command", "copy-command-button", "install-footer"],
  "/models": ["models-manage-root", "providers-root", "provider-search", "provider-list", "provider-item", "provider-expand-toggle", "sync-models-button", "provider-add-button"],
};
