-- 删除 `tasks.plan_mode` 列（legacy 计划模式开关下线，contract 阶段，单向不可逆）。
--
-- 列的历史用途（为什么存在）：`task.planMode` 是 2026-09 自造「新计划域」的开关，
--   1) 写入路径：`POST /tasks` / `PATCH /tasks/:id` DTO + `vteam_plan_mode` MCP 工具；
--   2) 读取路径：任务 DTO 的 `planMode`/`effectivePlanMode`（后者与主成员绑定 agent
--      的职责约定取 OR）+ `worker-dispatcher` 的计划指令注入。
--
-- 下线决策（option a，用户批准）：平台不再代控计划行为——是否计划由**所绑定 agent 自身
--   的 prompt** 表达。上面两条写入路径与两条读取路径已全部删除（server 侧零引用），
--   本迁移只删残留列。
--
-- 与「活计划域」的关系：`plans` 表 / `PlanLifecycleService` / `plan-docs` / 计划评审
--   （`plan_status`、`verifiedPlan*`、`/tasks/:id/plan/confirm|complete`）是独立且**仍在用**
--   的计划域，全部不读本列，删除本列对其零影响。
--
-- ⚠️ 单向迁移：drop 无反向 SQL，且本文件不可原样重跑（第二次 DROP COLUMN 报 1091）。
--   可重入性由 Prisma 迁移账本保证（已应用则不再执行）。回滚 = 恢复迁移前全库 dump。
ALTER TABLE `tasks` DROP COLUMN `plan_mode`;
